spring:
  application.name: gateway

  cloud:
    gateway:
    
      discovery:
         locator:
             enabled: true
    
      routes:
        # Public Service
      - id: publicHomePage
        uri: http://localhost:9000
        predicates:
            - Path=/

      - id: requestToken
        uri: http://localhost:9000/normal/requestToken
        predicates:
            - Path=/public/request-token

      - id: refreshToken
        uri: http://localhost:9000/normal/refreshToken
        predicates:
            - Path=/public/refresh-token

        # Authorization Server
      - id: oauth2Authorize
        uri: http://localhost:8085/oauth/authorize
        predicates:
            - Path=/oauth/authorize
        
      - id: oauth2GetToken
        uri: http://localhost:8085/oauth/token
        predicates:
            - Path=/oauth/token
        
      - id: oauth2CheckToken
        uri: http://localhost:8085/oauth/check_token
        predicates:
            - Path=/oauth/check_token

      - id: oauth2ConfirmAccess
        uri: http://localhost:8085/oauth/confirm_access
        predicates:
            - Path=/oauth/confirm_access

      - id: oauth2Error
        uri: http://localhost:8085/oauth/error
        predicates:
            - Path=/oauth/error

      - id: oauth2TokenKey
        uri: http://localhost:8085/oauth/token_key
        predicates:
            - Path=/oauth/token_key

        # Account Service
      - id: accountInfo
        uri: http://localhost:8084/normal/information
        predicates:
            - Path=/account/information

        # Order Service
      - id: orderInfo
        uri: http://localhost:8083/newcontrol/showinfo
        predicates:
            - Path=/order/information

logging:
  level:
    org.springframework.cloud.gateway: TRACE
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
