spring:
  application.name: gateway
  cloud:
    gateway:
      discovery:
         locator:
             enabled: false
      routes:
      - id: microservice1WelcomeRoute
        uri: http://localhost:8083/view/welcome
        predicates:
            - Path=/microservice1/welcome
      - id: microservice2WelcomeRoute
        uri: http://localhost:8084/view/welcome
        predicates:
            - Path=/microservice2/welcome
      - id: microservice3WelcomeRoute
        uri: http://localhost:8085/view/welcome
        predicates:
            - Path=/microservice3/welcome
      - id: microservice1WelcomeRoute1
        uri: http://localhost:8083/view/welcome
        predicates:
            - Path=/microservice1/welcome1
        filters :
            - AddRequestHeader=addHeader, Header Value ...

            
      - id: microservice1WelcomeRoute2
        uri: http://localhost:8083/view/welcome
        predicates:
            - Path=/microservice1/welcome2
        filters :
            - AddRequestParameter=addParam,Param+Value+...

      - id: microservice1WelcomeRoute3
        uri: http://localhost:8083/view/welcome
        predicates:
            - Path=/microservice1/welcome3
        filters :
            - AddRequestHeader=addHeader, [NEW] The Header Value
            - AddRequestParameter=addParam,%5BNEW%5D+Param+Value
server:
  port: 8080
